// generated by unplugin-vue-components
// We suggest you to commit this file into source control
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountForm: typeof import('./components/AccountForm.vue')['default']
    TransactionForm: typeof import('./components/TransactionForm.vue')['default']
    GoalForm: typeof import('./components/GoalForm.vue')['default']
    BudgetForm: typeof import('./components/BudgetForm.vue')['default']
    LoanForm: typeof import('./components/LoanForm.vue')['default']
  }
}

export {} 